<%@ Page Language="C#" AutoEventWireup="true" CodeFile="psydhaka.aspx.cs" Inherits="psydhaka" %>

<!DOCTYPE html>

<html>
<head>
    <title>Healthbd</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Medicinal Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script type="applisalonion/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <link href="css/style.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="css/slider.css">
    <script src="js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="js/move-top.js"></script>
    <script type="text/javascript" src="js/easing.js"></script>
    <!--/web-font-->
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!--/script-->







    <meta charset="UTF-8" />
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
    <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
    <meta name="author" content="Codrops" />
    <link rel="shortcut icon" href="../favicon.ico">
    <link rel="stylesheet" type="text/css" href="css1/demo.css" />
    <link rel="stylesheet" type="text/css" href="css1/style.css" />
    <link rel="stylesheet" type="text/css" href="css1/animate-custom.css" />








    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 900);
            });
        });
    </script>


    <style type="text/css">
        .auto-style3 {
            width: 39%;
            margin: 0 auto;
        }

        div {
            text-align: center;
        }
        .auto-style4 {
            width: 100%;
            height: 422px;
        }
        .auto-style5 {
            width: 212px;
        }
    </style>


</head>
<body>
    <!--start-home-->

    <div class="main-header" id="house">

        <div class="header-middle">
            <div class="auto-style3">
                <form action="#" method="post">
                    <div class="search">
                        &nbsp;
                    </div>
                    <div class="sear-sub">
                        &nbsp;
                    </div>
                    <div class="clearfix">
                    </div>
                </form>
            </div>
        </div>
        <!--header-top-->
        <div class="header-top">
            <div class="container">
                <nav class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="logo">
                            <h1><a class="navbar-brand" href="temp.aspx"><span>H</span>ealthbd     <img src="images/logo.png" alt=" " /></a></h1>
                        </div>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                        <div class="top-menu">
                            <nav class="menu menu--francisco">
                                <ul class="nav navbar-nav menu__list">
                                    <li class="menu__item"><a href="temp.aspx" class="menu__link"><span class="menu__helper">Home</span></a></li>
                                    <li class="menu__item"><a href="doccatagory.aspx" class="menu__link"><span class="menu__helper">Doctors</span></a></li>
                                    <li class="menu__item"><a href="bloodbank.aspx" class="menu__link"><span class="menu__helper">Blood Bank</span></a></li>
                                    <li class="menu__item"><a href="donate.aspx" class="menu__link"><span class="menu__helper">Donate blood</span></a></li>
                                    <li class="menu__item"><a href="healthtips.aspx" class="menu__link"><span class="menu__helper">Health Tips</span></a></li>
                                    <li class="menu__item"><a href="donar.aspx" class="menu__link"><span class="menu__helper">Donar List</span></a></li>
                                    <li class="menu__item"><a href="log.aspx" class="menu__link"><span class="menu__helper">Login</span></a></li>
                                    <li class="menu__item"><a href="reg.aspx" class="menu__link"><span class="menu__helper">Register</span></a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <table class="auto-style4">
        <tr>
            <td class="auto-style5">&nbsp;</td>
            <td>Psychiatrists in Dhaka<br />
                <br />
                <br />
                <br />
                <span style="color: rgb(51, 51, 51); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; font-family: times, &quot;times new roman&quot;, serif;"><b style="font-size: x-large;"><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Prof. Dr. Nazimuddowla Chowdhury</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Qualification :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS ( Dhaka ), DPM ( UK ), FCPS (Psychiatry), FRCP ( UK )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Designation :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Former Head, Department Of Psychiatry, BSMMU</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Expertise :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Medical Consultation Center</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Location:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">46/16, Panthapath, Dhaka 1205</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">+880-2-8121608, 8124882 ( Chamber )</span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b><br />
                </b></span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber : Monojagot Center</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Road No. 4, House No. 5 (1st Floor), Dhanmondi, Dhaka.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">(Opposite of Dhaka City College &amp; Beside of Lab Aid Cardiac Hospital Ltd.)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">[Time for Appointments : 8:00 AM to 8:00 PM ] Phone : 9662475, 8613786</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Mobile : 01715-178888, 01819-240000</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Professor Dr. M S I Mullick</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Qualification :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS, Phd, FCPS, MRC Psyc ( London ) , DCAP</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Designation :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Professor &amp; Chairman, Department of Pshychiatric</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Expertise :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Organization:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Bangabandhu Sheikh Mujib Medical University (BSMMU), Shahbagh, Dhaka</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Labaid Hospital Ltd.</span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span>
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Location:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">House # 1, Road # 4, Dhanmondi, Dhaka - 1205</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">+ 880-2-8610793-8, 9670210-3 ( Chamber )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>
                <br />
                <br />
                </b></span></b></span>
                <br style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
                <span style="color: rgb(51, 51, 51); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; font-family: times, &quot;times new roman&quot;, serif;"><span style="font-size: large;"><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: small; font-weight: normal;"><span style="font-family: times, &quot;times new roman&quot;, serif; font-size: large;">Prof. Dr Anwara Begum</span><br />
                <span style="font-family: times, &quot;times new roman&quot;, serif; font-weight: normal;">Qualification: MBBS, FCPS, MRCPsych (London)</span><br />
                <span style="font-family: times, &quot;times new roman&quot;, serif; font-weight: normal;">Designation: Professor of Psychiatry and Chief Consultant,&nbsp;</span></span></span></span><br style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
                <span style="color: rgb(51, 51, 51); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; font-family: times, &quot;times new roman&quot;, serif;"><span style="font-size: large;"><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: small; font-weight: normal;"><span style="font-weight: normal;">BIRDEM General Hospital and Ibrahim Medical College, Dhaka, Bangladesh.</span><br />
                <span style="font-weight: normal;">Expertise: Psychiatry</span><br />
                <span style="font-weight: normal;">Website:<span>&nbsp;</span></span><a href="http://www.google.com/url?q=http%3A%2F%2Fwww.anwarabegum.com&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEPZ1jPNcjh0E-9rkaT34-5eMdZvg" rel="noreferrer" style="color: rgb(0, 158, 184); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; outline: none; text-decoration: none; transition: color 0.3s; display: inline; font-weight: normal;" target="_blank">www.anwarabegum.com</a><br />
                <span style="font-weight: normal;">Chambers (3 locations below):</span><br />
                <br />
                <span style="font-weight: normal;">BIRDEM General Hospital</span><br />
                <span style="font-weight: normal;">Specialist Chamber Complex (1st Floor),</span><br />
                <span style="font-weight: normal;">122, Kazi Nazrul Islam Avenue,</span><br />
                <span style="font-weight: normal;">Dhaka 1000, Bangladesh.</span><br />
                <span style="font-weight: normal;">Tel: +88-02-9661551-60, Ext: 2576.</span><br />
                <span style="font-weight: normal;">Time: 3-7pm. Closed on Fridays and Government Holidays.</span><br />
                <br />
                <span style="font-weight: normal;">Ibrahim General Hospital &amp; DCEC</span><br />
                <span style="font-weight: normal;">House # 42, Road # 10/A,</span><br />
                <span style="font-weight: normal;">Dhanmondi Residential Area,</span><br />
                <span style="font-weight: normal;">Dhaka 1209, Bangladesh.</span><br />
                <span style="font-weight: normal;">Tel:<span>&nbsp;</span></span><a href="tel:+880-02-9146357" rel="noreferrer" style="color: rgb(0, 158, 184); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; outline: none; text-decoration: none; transition: color 0.3s; display: inline; font-weight: normal;" target="_blank" value="+88029146357">+880-02-9146357</a><br />
                <span style="font-weight: normal;">Time:</span><br />
                <br />
                <span style="font-weight: normal;">Sheba House</span><br />
                <span style="font-weight: normal;">Plot # 34 (4th floor), Road # 46,</span><br />
                <span style="font-weight: normal;">Gulshan 2 Residential Area,</span><br />
                <span style="font-weight: normal;">Dhaka 1212, Bangladesh.</span></span></span></span><br style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" />
                <span style="color: rgb(51, 51, 51); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; font-family: times, &quot;times new roman&quot;, serif;"><b style="font-size: x-large;"><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>
                <br />
                <br />
                Professor Dr. Md. Enayet Karim</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS, FCPS (Psychiatry)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatrist</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber :Hi Tech</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Modern Psychiatric Hospital (Pvt.) Ltd.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">113/A, Monipuripara, Gate No. 1</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Farmgate, Tejgaon,</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Dhaka-1215, Bangladesh.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone : 02-9131958 (chamber)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Mob : 01730-351728</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Professor Dr. Dewan Abdur Rahim</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">PhD, DPM, MCPS (Psych), MBBS</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Fellow WHO (India), Fellow JICA (Japan)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatrist</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Ex. Head of Dept. Psychiatry SSMC Mitford Hospital, Dhaka</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber :</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Sandhani Diagnostic Complex</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Green Super Market (3rd Floor)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Farmgate, Dhaka, Bangladesh.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone : 02-9126670, Mob : 01675 494919</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Visiting Hours : 6:30 PM - 8:30 PM</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">[ Sunday to Wednesday ]</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Prof. (Dr.) Mahmood Hasan</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">M.B.B.S, F.C.P.S (PSY), F.C.P.S(PAK)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">F.I.P.S(India), FWASD (Canada)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Member : American Syck. Association</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatrist</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Professor &amp; Head of the Dept. of Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Bangladesh Medical College And Hospital</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber : IBN Sina Medical Imaging Center</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Road No. 2/A, House No. 58, Dhanmondi R/A</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">(Near Zigatola Bus Stand)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Dhaka-1209, Bangladesh.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone : 8610420, 9666497, 9663289</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Visiting Hours : 5:30 PM - 9:30 PM</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">[ Tuesday &amp; Friday Closed ]</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Professor Dr. Md. Ahsanul Habib</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Qualification :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS, FCPS ( Psyhch )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Designation :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Professor, Ex - Director, Mental Hospital, Pabna</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Expertise :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Northern International Medical College &amp; Hospital</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Location:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">House # 48, Road # 9/A, Satmasjid Road, Dhanmondi, Dhaka - 1209, Bangladesh</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">+880-2-8156914, 8156839, 9133505, 9111381,</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Cell: +880 1674058435, +880 1715153935 ( Chamber )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber :Hi Tech</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Modern Psychiatric Hospital (Pvt.) Ltd.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">113/A, Monipuripara, Gate No. 1</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Farmgate, Tejgaon,</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Dhaka-1215, Bangladesh.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone : 02-9131958 (Office)</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Mob : 01711-104303, 01730-351728</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Prof. Brig. Gen. Dr. Md. Sajjadur Rahman</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Qualification :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS, FCPS ( Psychiatry )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Designation :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Professor &amp; Head, Department of Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Expertise :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Organization:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Armed Forces Medical College &amp; Hospital</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Aysha Memorial Specialised Hospital</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Location:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">74/G/ 75, Peacock Square, New Airport Road,Mohakhali, Dhaka -1215, Bangladesh</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">+880-2-9122689, 9122690, 8142370, 8142371( Chmaber )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Professor Dr. Md. Golam Rabbani</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Qualification :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS, FCPS</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Designation :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Professor</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Expertise :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Organization:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">National Institute of Mental Health</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Medinova Medical Services Ltd.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Location:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">House # 71/A, road # 5/A, Dhanmondi R/A, Dhaka.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">+880-2-8620353-6, 8624907-10</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <b style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;">Professor Dr. A.A. Quoreshi</b><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Qualification :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS, PGT ( USA )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Designation :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Consultant, Chief &amp; Managing Director</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Expertise :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Organization:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MUKTI ( Manashik &amp; Madakashakti Niramoy Kendra Ltd. )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MUKTI ( Manashik &amp; Madakashakti Niramoy Kendra Ltd. )</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Location:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">House # 2, Road # 49, Gulshan # 2, Dhaka - 1212, Bangladesh</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">+880 2 9896165, 9883991, 8814562</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: medium; font-weight: normal;"><b>Professor Dr. Saroj Kumar Das</b></span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Qualification :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">MBBS, FCPS</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Designation :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Professor</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Expertise :</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Psychiatry</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Organization:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">National Institute of Mental Health</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Chamber:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Medinova Medical Services Ltd.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Location:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">House # 71/A, road # 5/A, Dhanmondi R/A, Dhaka.</span><br style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue Light&quot;, HelveticaNeue-Light, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; line-height: 19.6px;" />
                <span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">Phone:</span><span class="Apple-tab-span" style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px; white-space: pre;"> </span><span style="background-color: rgb(250, 250, 250); color: rgb(51, 51, 51); font-size: 14px; font-weight: normal; line-height: 19.6px;">+880-2-8620353-6, 8624907-10<br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                </span></b></span></td>
        </tr>
    </table>


